# Generated by Django 3.1.7 on 2022-07-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=500)),
                ('chapter_name', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=50)),
                ('content_file_path', models.CharField(max_length=5000)),
            ],
        ),
    ]
